#!/bin/bash

instances="abba aman-aplan anchors four order ranges triples words"

depth=9

DIRECTORY=`dirname $0`
FILE="$DIRECTORY/ILS_S.csv"

for instance in $instances
do
    for index in {0..29}
    do
        echo npm run localsearch -- --name=$instance --depth=$depth --index=$index --csv
        npm run localsearch -- --name=$instance --depth=$depth --index=$index --csv >> $FILE
    done
done